### PR TITLE
Adds handling of recursive mappings

### PR DESCRIPTION
**Pull request by josepmedrano**
As discussed on issue 53 (https://github.com/Yalantis/FastEasyMapping/issues/53)

### CODE REVIEW

**Comment by dimazen** [comment]
@josepmedrano thanks! I'll take a closer look tomorrow.

**Comment by Antondomashnev** [comment]
@dimazen hi, what's the status of this pull request review?

**Comment by Antondomashnev** [comment]
@josepmedrano please add `nullability type specifier` for all parameters of `- (void)addRecursiveRelationshipMappingForProperty:(NSString *)property keypath:(NSString *)keyPath;`

**Comment by dimazen** [comment]
Hello, @Antondomashnev. Sorry for such a huge delay - I was busy on the project and then totally forgot about FEM and pending PRs. 

Going to take a look at your PR today and merge if it is OK (it should be, I reviewed it before). 
Also, I can roll out release today (1.1, lets say). 

Regarding failing tests: they should be fine - I've fixed Travis CI integration, however, it won't rerun existing PRs unless you'll try to push something :)

**Comment by Antondomashnev** [comment]
@dimazen that's sounds awesome

**Comment by dimazen** [comment]
@Antondomashnev I have a weekend tomorrow, so decided to postpone it until tomorrow's morning. Hope it is ok.

**Comment by Antondomashnev** [comment]
@dimazen don't worry I'm using the pod from my fork now, it's not urgent

**Comment by dimazen** [comment]
This PR has failing tests, I've merged it into current feature/FEM-53 branch where I'm also going to merge @Antondomashnev's changes.

**Comment by Antondomashnev** [comment]
Thanks @dimazen 🚀

**Comment by dimazen** [comment]
I'm planning to make a release on this weekends, that will also include documentation in headers.

**Comment by dimazen** [comment]
@Antondomashnev you can now grab 1.1 release from the CocoaPods :)

**Comment by Antondomashnev** [comment]
@dimazen amazing, thanks lot =)

**Pull request merged**
