### PR TITLE
Update ci to latest tooling

### PR DESCRIPTION
**Pull request by jcavar**
CI currently fails for any change, and it seems that it is due to outdated tooling.

### CODE REVIEW

**Comment by dimazen** [comment]
Thanks for your support! I gonna review your changes tomorrow and merge them with a new release.

**Comment by jcavar** [comment]
No problem, it is not ready yet, but I am getting there.

**Comment by jcavar** [comment]
Ok, we finally have all green, so I think it is ready to go @dimazen.

**Comment by dimazen** [comment]
Thanks a lot for your support and help, @jcavar!

**Pull request merged**
